apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-77-tenant/load-app-bda45fb3-96a9-4b64-949a-8c9b432865e5/devfile-sample@sha256:010303f569c70c5b6db60aa5919b1fb4fd0fd4fdd9c1954a20588ffa008eab05
        name: my-nodejs
        resources: {}
status: {}
